# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:year/:month/:day/:title/

plugins:
  - jekyll-paginate
  - jekyll-gist


# Setup
title:            'COVID-19 in Warren County, IL'
tagline:          'Tracking COVID-19 from Warren County, IL'
description:      'A data-focused look at the pandemic of 2020 as experienced in and around western Illinois'
url:              http://jlmayfield.github.io/wcil-covid-reporting/
baseurl:          '/wcil-covid-reporting'

author:
  name:           'Logan Mayfield'
  url:            https://jlmayfield.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jlmayfield/wcil-covid-reporting/
