# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty

plugins: [jekyll-paginate]

# Setup
title:            'COVID-19 in Warren County, IL'
tagline:          'Tracking COVID-19 from Warren County, IL'
description:      'A Data-Focused Look at the pandemic of 2020 as experienced in and around Western Illinois'
url:              http://wcil-covid-reporting.github.io
baseurl:          ''

author:
  name:           'Logan Mayfield'
  url:            https://jlmayfield.github.io

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jlmayfield/wcil-covid-reporting/
